name: .NET CI Build for MyGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        config-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build packages
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Push to MyGet
      env:
        API_KEY: ${{ secrets.MYGET_FILEMAKER_FEED_API_TOKEN }}
      if: ${{ env.API_KEY != '' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}
      run: |
        dotnet nuget push FMData/**/*.nupkg --source https://www.myget.org/F/filemaker/api/v2/package --api-key ${{ env.API_KEY }}